### PR TITLE
Switch to alpine linux containers

### PR DESCRIPTION
**Pull request by tkreind**
[linuxserverurl]: https://linuxserver.io
[linuxserver.io][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-radarr/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:

Transitioned Dockerfiles to use Alpine linux containers with the musl built self-contained executable.

## Benefits of this PR and context:

The benefits of using alpine for containers are well known in size and security. In this case the container size goes down from 308 MB -> 200 MB. All users will benefit from lower memory overhead and a smaller container size.

## How Has This Been Tested?

I simply build it locally and then ran it on a Ubuntu 20.04 x64 host, and accessed the web portal to make sure it was working properly, and checked the settings menu to make sure there were no errors.

I haven't tested this in production yet, if that's necessary I can do so and report back.

### CODE REVIEW

**Comment by tkreind** [comment]
Forgot to add additional context: previously this container used a Ubuntu base likely because of the mono dependency, but as the program has transitioned to dotnet core this dependency is no longer an issue and a self-contained musl build is provided.

**Comment by tkreind** [comment]
Update: had a minor typo in my reformatting, fixed in latest commit.

**Comment by tkreind** [comment]
Realized that the Radarr team doesn't provide a prebuilt armhf musl binary, so I reverted that Dockerfile to its original Ubuntu state. I still think the benefits of shipping this for x64 and arm64 are great enough to justify splitting this, but will be reaching out to the Radarr team to see if we can get a armhf musl binary built.

**Comment by tkreind** [comment]
It would seem that Radarr v4 that is currently in pre-release builds the armhf musl binaries we need, it might make sense to delay this pull request until that time that that becomes stable and the Dockerfiles can have parity.

**Comment by Roxedus** [comment]
This is already in the works. Radarr do output armhf binaries. 

https://github.com/linuxserver/docker-radarr/tree/nightly-alpine

**Pull request closed without merging**
