### PR TITLE
Switch create to run, use --rm and add padding.

### PR DESCRIPTION
**Pull request by fryfrog**
Just making the README.md a little similar to hotio's radarr docker image.

### CODE REVIEW

**Comment by aptalca** [comment]
Why would you want to make it more like some other developer's image?

**Comment by fryfrog** [comment]
Because the other developer's README.md was a little more logical in this tiny way?

I did a pull request to the *other* developer's README.md to fix the tiny bits of theirs that linuxserver's got better.

Who cares where it came from, it is a small improvement to your README.md. Did you *object* to the changes for some reason? Is create better than run? Is --rm a poor choice? I'm open to comment on that.

I think using run instead of create is better because you *still* have to run it after you create it. Instead, you can save a step and do it this way. You can also plop it down into a systemd unit file and it works.

And for the --rm, it makes updating simpler because you can `docker pull` and then just restart the container.

**Comment by CHBMB** [comment]
@fryfrog I think it's more to do with the fact we have a template for all our images, change this one, and we gonna have to change them all.....

**Comment by fryfrog** [comment]
AHH! That I didn't know. In that case, a punt is the right call :)

**Comment by aptalca** [comment]
With regards to run vs create, it's more of a preference. Using create is more neutral. We show users how to create a container, they can deal with its running status as they wish. 

Using run with those options is trickier because, like I said, personal preference. Not everyone likes to use -rm because they may be stopping and starting the containers frequently and may not want to deal with the overhead of creating a new container every time it is restarted. Also with your suggestion of the run command, you need to consider the -d flag because on many headless systems, if you start it without the -d flag, it stops when you disconnect your ssh client. So, there are many options and preferences.

**Comment by fryfrog** [comment]
Thanks, the --rm and -d flag conflict and issue from it are great points, I'll suggest some changes to hotio's based on that. :)

**Comment by fryfrog** [comment]
Fwiw, it looks like --rm and -d can be used together now.

https://github.com/docker/docker/pull/20848

I still totally agree that changing your entire template is crazy :)

**Comment by CHBMB** [comment]
@fryfrog Thanks anyways, always nice to have input.

**Pull request closed without merging**
